SFTPTOGO_URL    = "sftp://user:pass@url.com"
remote_path     = "/home/user/apps/appname/wp-content/uploads/"
images_path     = "/home/user/Documents/"
username        = "username"
password        = "password"
mainurl         = "https://test.test.com"
wordpress_path  = "/wp-content/uploads/"